# Generated by Django 5.1.6 on 2025-10-06 07:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_code', models.CharField(help_text="Course code (e.g., 'CS101')", max_length=20, unique=True)),
                ('course_name', models.CharField(help_text='Full course name', max_length=200)),
                ('credits', models.DecimalField(decimal_places=1, help_text='Credit hours for this course (e.g., 7.5, 9.0, 9.5, 10.0)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(20.0)])),
                ('department', models.CharField(help_text='Academic department', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'COURSES',
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lecturer_id', models.CharField(help_text='University-assigned lecturer ID', max_length=50, unique=True)),
                ('department', models.CharField(help_text="Academic department (e.g., 'Computer Science')", max_length=200)),
                ('specialization', models.CharField(blank=True, help_text='Area of expertise', max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LECTURERS',
                'db_table': 'lecturers',
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.CharField(choices=[('FALL', 'Fall Semester'), ('SPRING', 'Spring Semester'), ('SUMMER', 'Summer Semester')], max_length=10)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=9)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='srs_domain.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(help_text='Lecturer teaching this course for this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_enrollments', to='srs_domain.lecturer')),
            ],
            options={
                'verbose_name_plural': 'ENROLLMENTS',
                'db_table': 'enrollments',
                'ordering': ['-academic_year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='CourseResults',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade_type', models.CharField(choices=[('NUMERIC', 'Numeric (0-100)'), ('LETTER', 'Letter Grade (A-F)')], default='NUMERIC', max_length=10)),
                ('numeric_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('letter_grade', models.CharField(blank=True, help_text='Letter grade (A, B+, C, etc.)', max_length=2, null=True)),
                ('course_work_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Course work/assignment grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Final exam grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True, help_text='Remarks (Pass, Fail, Carry Over, etc.)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('OFFICIAL', 'Official (Immutable)'), ('DISPUTED', 'Under Dispute')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the grade became official', null=True)),
                ('comments', models.TextField(blank=True, help_text='Optional comments from lecturer')),
                ('blockchain_hash', models.CharField(blank=True, help_text='SHA-256 hash stored on blockchain', max_length=256)),
                ('blockchain_transaction_id', models.CharField(blank=True, help_text='Blockchain transaction ID for verification', max_length=256)),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS Content Identifier for encrypted record', max_length=256)),
                ('is_verified', models.BooleanField(default=False, help_text='Has cryptographic integrity been verified?')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(help_text='Links to student enrollment in course', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='srs_domain.enrollment')),
                ('submitted_by', models.ForeignKey(help_text='Lecturer who submitted this grade', on_delete=django.db.models.deletion.PROTECT, related_name='grades_submitted', to='srs_domain.lecturer')),
            ],
            options={
                'verbose_name_plural': 'GRADES',
                'db_table': 'grades',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_lecturer',
            field=models.ForeignKey(help_text='Primary lecturer for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='srs_domain.lecturer'),
        ),
        migrations.CreateModel(
            name='RecordTransaction',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('CREATE', 'Record Created'), ('VERIFY', 'Record Verified'), ('ACCESS', 'Record Accessed')], max_length=10)),
                ('transaction_id', models.CharField(help_text='Blockchain transaction ID', max_length=256)),
                ('transaction_hash', models.CharField(help_text='Hash value stored on blockchain', max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction details')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='srs_domain.courseresults')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_transactions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RECORD TRANSACTIONS',
                'db_table': 'record_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StorageReference',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('storage_type', models.CharField(choices=[('IPFS', 'IPFS Distributed Storage'), ('LOCAL', 'Local File Storage')], default='IPFS', max_length=10)),
                ('content_identifier', models.CharField(help_text='CID for IPFS or file path for local', max_length=256)),
                ('encrypted', models.BooleanField(default=True, help_text='Is the stored data encrypted?')),
                ('encryption_algorithm', models.CharField(blank=True, help_text="Encryption algorithm used (e.g., 'AES-256-CBC')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_references', to='srs_domain.courseresults')),
            ],
            options={
                'verbose_name_plural': 'STORAGE REFERENCES',
                'db_table': 'storage_references',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_id', models.CharField(help_text='University-assigned student ID', max_length=50, unique=True)),
                ('enrollment_date', models.DateField(help_text='When the student first enrolled')),
                ('program', models.CharField(help_text="Degree program (e.g., 'BSc Computer Science')", max_length=200)),
                ('year_of_study', models.IntegerField(help_text='Current year (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'STUDENTS',
                'db_table': 'students',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='srs_domain.student'),
        ),
        migrations.CreateModel(
            name='AcademicTranscript',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.CharField(help_text='Year this transcript covers', max_length=9)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_root_hash', models.CharField(help_text='Merkle root of all grades in transcript', max_length=256)),
                ('ipfs_cid', models.CharField(help_text='IPFS CID for complete transcript document', max_length=256)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts_generated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='srs_domain.student')),
            ],
            options={
                'verbose_name_plural': 'ACADEMIC TRANSCRIPTS',
                'db_table': 'academic_transcripts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courseresults',
            index=models.Index(fields=['blockchain_transaction_id'], name='grades_blockch_79fd84_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresults',
            index=models.Index(fields=['ipfs_cid'], name='grades_ipfs_ci_0ead4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'semester', 'academic_year')},
        ),
    ]
