# Generated by Django 5.1.6 on 2025-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs_domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academictranscript',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated GPA', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='academictranscript',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Whether this is an official transcript'),
        ),
        migrations.AddField(
            model_name='academictranscript',
            name='semester',
            field=models.CharField(blank=True, choices=[('FALL', 'Fall Semester'), ('SPRING', 'Spring Semester'), ('SUMMER', 'Summer Semester')], help_text='Semester this transcript covers (if specified)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='academictranscript',
            name='total_credits',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total credits earned', max_digits=5, null=True),
        ),
    ]
