# Generated by Django 5.1.6 on 2025-10-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs_domain', '0002_academictranscript_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresults',
            name='comments',
            field=models.TextField(blank=True, help_text='Optional comments from lecturer', null=True),
        ),
        migrations.AlterField(
            model_name='courseresults',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks (Pass, Fail, Carry Over, etc.)', null=True),
        ),
    ]
