# Generated by Django 5.1.6 on 2025-12-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs_domain', '0003_alter_courseresults_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtransaction',
            name='previous_hash',
            field=models.CharField(blank=True, help_text='Previous blockchain hash (for linking versions)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recordtransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional transaction details including change tracking'),
        ),
        migrations.AlterField(
            model_name='recordtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('VERIFY', 'Record Verified'), ('ACCESS', 'Record Accessed')], max_length=10),
        ),
    ]
