# Generated by Django 5.1.6 on 2025-10-04 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.CharField(max_length=10000, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('first_attempt_time', models.DateTimeField(auto_now_add=True)),
                ('blocked_time', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(db_index=True, max_length=255, null=True, verbose_name='User Agent')),
                ('http_accept', models.CharField(max_length=1025, null=True, verbose_name='HTTP Accept')),
                ('path_info', models.CharField(max_length=255, null=True, verbose_name='Path')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LOGIN ATTEMPTS',
                'db_table': 'login_attempts',
                'ordering': ['-first_attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionsGroup',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=9000)),
                ('is_global', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=600, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PERMISSIONS GROUP',
                'db_table': 'user_permissions_group',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=9000)),
                ('code', models.CharField(default='', max_length=9000)),
                ('permission_is_seeded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_group', to='srs_uaa.userpermissionsgroup')),
            ],
            options={
                'verbose_name_plural': 'USER PERMISSIONS',
                'db_table': 'user_permissions',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=9000)),
                ('description', models.CharField(default='', max_length=9000)),
                ('is_seeded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USER ROLES',
                'db_table': 'user_roles',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserRolesWithPermissions',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_read_only', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_with_permission_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_with_permission_permission', to='srs_uaa.userpermissions')),
                ('role_with_permission_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_with_permission_role', to='srs_uaa.userroles')),
            ],
            options={
                'verbose_name_plural': 'ROLES WITH PERMISSIONS',
                'db_table': 'user_role_with_permissions',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UsersWithRoles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_with_role_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_name', to='srs_uaa.userroles')),
                ('user_with_role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERS WITH ROLES',
                'db_table': 'user_with_roles',
                'ordering': ['-primary_key'],
            },
        ),
    ]
